### ISSUE TITLE
Setup build

### ISSUE THREAD

**Issue by xivk** [NetTopologySuite/NetTopologySuite.Features#1]
Setup build similar to the core project.

**Comment by xivk** [comment]
@FObermaier I see you tried to setup the build, I don't now why the packaging fails, the files are there:

![image](https://user-images.githubusercontent.com/1128068/42811859-2c33f30e-89bc-11e8-9b03-50742784134c.png)

**Comment by FObermaier** [comment]
The name of the nuspec file has changed from `NTS.Features.nuspec` to `NetTopologySuite.Features`

**Comment by xivk** [comment]
Ah :+1: I missed that somehow! haha

The build now works...
