### ISSUE TITLE
How to test IAttributesTable for for thread safety issues?

### ISSUE THREAD

**Issue by kirkktx** [NetTopologySuite/NetTopologySuite.Features#15]
I see that IAttributesTable[ is implemented as a Dictionary](https://github.com/NetTopologySuite/NetTopologySuite.Features/blob/e9bdd56e0544c344be84459cf2f714307642d549/src/NetTopologySuite.Features/AttributesTable.cs#L15), which is [not thread safe](https://stackoverflow.com/questions/22790505/how-to-add-item-to-dictionary-parallel-loop-safe/22790563#22790563).

The code base I'm working with has a lot situations where `Parallel.Foreach` is used to loop through an `IEnumerable<Feature>`. 

Within the loop, there are cases where `IAttributesTable` gets updated.

Is there a test I could run that would confirm that this can cause problems?

Assuming there is a reproducible issue, would implementing `IAttributesTable` with a `ConcurrentDictionary` work?  Has anyone tried this?
Thanks!

**Comment by FObermaier** [comment]
Sorry for the late reply, but I assume that the lack of thread safety for `Dictionary<TKey,TValue>` might only cause issues when one feature's attributes are accessed/modified from different threads at the same time.
The scenario you describe should be fine.
