### ISSUE TITLE
1.15 Release?

### ISSUE THREAD

**Issue by nickalbrecht** [NetTopologySuite/NetTopologySuite.Features#2]
Just tried to update to the NTS 1.15 Release, and after noticing Features were gone, I did some digging and finally stumbled across this :-P Was wondering when `NetTopologySuite.Features` will be pushed to Nuget as well?

**Comment by FObermaier** [comment]
The v1.15.0 package is available both on 
* our myget feed 
https://www.myget.org/feed/nettopologysuite/package/nuget/NetTopologySuite.Features/1.15.0
* as well as on nuget
https://www.nuget.org/packages/NetTopologySuite.Features/1.15.0
