### ISSUE TITLE
Simplify fetching values for optional attributes in (I)AttributesTable

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite.Features#3]
GPX has a **ton** of well-defined attributes that can be present on each `wpt`, `rtept`, and `trkpt` element, but almost all of them are optional, and very few of them are actually specified on any given instance (different producers seem to favor different sets of them).

This makes it rather awkward to consume an `IAttributesTable` in order to produce elements from the GPX data model, since every optional value retrieved has to look like:

```csharp
var feature = /* some feature */;
var attributes = feature.Attributes;
var timestampUtc = attributes.Exists(nameof(GpxWaypoint.TimestampUtc))
    ? (DateTime)attributes[nameof(GpxWaypoint.TimestampUtc)]
    : default(DateTime?);
```

I don't think this concept is necessarily limited to GPX (otherwise I'd just live with extension methods).  It feels like this abstraction should simplify fetching optional attributes without requiring an extra virtual call and dictionary lookup for each one.

In my fantasy land, I can see myself writing:
```csharp
var feature = /* some feature */;
var attributes = feature.Attributes;
var timestampUtc = (DateTime?)attributes.GetOptionalValue(nameof(GpxWaypoint.TimestampUtc));
```

The implementation would be a bit annoying:
```csharp
public class AttributesTable
{
    /* ...*/
    public object GetOptionalValue(string attributeName)
    {
        object result = null;
        #if SERIALIZATION_COMPAT_NETTOPOLOGYSUITE_FEATURES_ATTRIBUTESTABLE
        // System.Collections.Hashtable doesn't have a way to skip this double-lookup
        if (_attributes.ContainsKey(attributeName))
        {
            result = _attributes[attributeName];
        }
        #else
        _attributes.TryGetValue(attributeName, out result);
        #endif

        return result;
    }
}
```

**Comment by FObermaier** [comment]
I support this.
