### ISSUE TITLE
Remove CRS stuff

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite.Features#7]
RFC 7946 GeoJSON doesn't have special recognition for it anymore, and it makes things awkward because it's kinda redundant with `Geometry.SRID`.

**Comment by FObermaier** [comment]
I support this.

**Comment by steveoh** [comment]
I think this is a mistake

> However, where all involved parties have a prior arrangement, alternative coordinate reference systems can be used without risk of data being misinterpreted.
